name: axomai_browser_mobile
description: "Axomai Browser - Privacy-first, intelligent mobile web browser."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  go_router: 14.8.1
  cupertino_icons: 1.0.8
  google_fonts: 8.2.1
  shared_preferences: 2.3.5
  intl: 0.20.2
  flutter_inappwebview: 6.1.5
  share_plus: 10.1.4
  sqflite: 2.4.1
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  sqflite_common_ffi: ^2.4.3
  sqlite3_flutter_libs: ^0.6.0+eol

flutter:
  uses-material-design: true
  generate: true
